default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - id: python-check-blanket-noqa
  - id: python-no-eval
  repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
- hooks:
  - id: no-fixme-todo
    name: No FIXME or TODO markers
    entry: '(FIXME:|TODO:)'
    language: pygrep
    types: [python]
  repo: local
- hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
    exclude: ^src/experimaestro/webui/data
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
- hooks:
  - id: conventional-pre-commit
    stages:
    - commit-msg
  repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
